apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: facebook-taobench-experiments
  labels:
    project: taobench
    app: taobench-app
spec:
  storageClassName: rook-ceph-block
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
