apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: facebook-taobench-experiments-shared
  labels:
    project: taobench
    app: taobench-app
spec:
  storageClassName: rook-cephfs
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
