apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: test.rados.uswest
spec:
  storageClassName: rook-ceph-block
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 4200Mi
