apiVersion: v1
kind: Pod
metadata:
  name: taobench-cockroachdb-client
  labels:
    app: taobench-cockroachdb-client
spec:
  serviceAccountName: cockroachdb
  containers:
  - name: taobench-cockroachdb-client
    image: cockroachdb/cockroach:v23.1.2
    imagePullPolicy: IfNotPresent
    volumeMounts:
    - name: client-certs
      mountPath: /cockroach-certs
    # Keep a pod open indefinitely so kubectl exec can be used to get a shell to it
    # and run cockroach client commands, such as cockroach sql, cockroach node status, etc.
    command:
    - sleep
    - "2147483648" # 2^31
    resources:
      requests:
        cpu: 500m
        memory: 256Mi
      limits:
        cpu: "1"
        memory: 256Mi
  # This pod isn't doing anything important, so don't bother waiting to terminate it.
  terminationGracePeriodSeconds: 0
  volumes:
  - name: client-certs
    secret:
      secretName: taobench.cockroachdb.client.root
      defaultMode: 256
