apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: taobench-cockroachdb
  labels:
    project: taobench
    app: taobench-cockroachdb
spec:
  serviceName: taobench-cockroachdb
  replicas: 3
  selector:
    matchLabels:
      app: taobench-cockroachdb
  template:
    metadata:
      labels:
        app: taobench-cockroachdb
    spec:
      nodeSelector:
        nautilus.io/disktype: nvme
      serviceAccountName: taobench-cockroachdb
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            # Assign to different hosts for better fault tolerance
            - topologyKey: kubernetes.io/hostname
              labelSelector:
                matchLabels:
                  "app": "taobench-cockroachdb"
        podAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            # Restrict to the same zone to keep latency low
            - topologyKey: topology.kubernetes.io/zone
              labelSelector:
                matchLabels:
                  "app": "taobench-cockroachdb"
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: topology.kubernetes.io/region
                    operator: In
                    values:
                      - REGION
      containers:
      - name: taobench-cockroachdb
        image: cockroachdb/cockroach:v23.1.2
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 26257
          name: grpc
        - containerPort: 8080
          name: http
# We recommend that you do not configure a liveness probe on a production environment, as this can impact the availability of production databases.
#      livenessProbe:
#        httpGet:
#          path: "/health"
#          port: http
#          scheme: HTTPS
#        initialDelaySeconds: 30
#        periodSeconds: 5
        readinessProbe:
          httpGet:
            path: "/health?ready=1"
            port: http
            scheme: HTTPS
          initialDelaySeconds: 10
          periodSeconds: 5
          failureThreshold: 2
        volumeMounts:
        - name: datadir
          mountPath: /cockroach/cockroach-data
        - name: certs
          mountPath: /cockroach/cockroach-certs
        env:
        - name: COCKROACH_CHANNEL
          value: kubernetes-multiregion
        - name: GOMAXPROCS
          valueFrom:
            resourceFieldRef:
              resource: limits.cpu
              divisor: "1"
        - name: MEMORY_LIMIT_MIB
          valueFrom:
            resourceFieldRef:
              resource: limits.memory
              divisor: "1Mi"
        command:
          - "/bin/bash"
          - "-ecx"
          # The use of qualified `hostname -f` is crucial:
          # Other nodes aren't able to look up the unqualified hostname.
          - exec
            /cockroach/cockroach
            start
            --logtostderr
            --certs-dir /cockroach/cockroach-certs
            --advertise-host $(hostname -f)
            --http-addr 0.0.0.0
            --join JOINLIST
            --locality LOCALITYLIST
            --cache 0.25
            --max-sql-memory 0.25
        resources:
            requests:
              cpu: "2"
              memory: "8Gi"
              ephemeral-storage: 64Gi
            limits:
              cpu: "2"
              memory: "8Gi"
              ephemeral-storage: 64Gi
      # No pre-stop hook is required, a SIGTERM plus some time is all that's
      # needed for graceful shutdown of a node.
      terminationGracePeriodSeconds: 60
      volumes:
      - name: datadir
        emptyDir: {}
      - name: certs
        secret:
          secretName: taobench.cockroachdb.node
          defaultMode: 256
  podManagementPolicy: Parallel
  updateStrategy:
    type: RollingUpdate
