apiVersion: v1
kind: Pod
metadata:
  name: test-rclone
spec:
  # Secret setup: https://kubernetes.io/docs/concepts/configuration/secret/#use-case-pod-with-ssh-keys
  volumes:
    - name: secret-vol-cephs3-rclone-config
      secret:
        secretName: cephs3-rclone-conf
  containers:
  - name: test-rclone-pod
    image: gitlab-registry.nrp-nautilus.io/c3lab/common/rclone:1.61.1
    # imagePullPolicy: Always
    resources:
      limits:
        memory: 100Mi
        cpu: 100m
      requests:
        memory: 100Mi
        cpu: 100m
    # command: ["sh", "-c", "echo 'Im a new pod' && sleep infinity"]
    command: ["sh", "-c", "rclone ls nrp-west: && rclone ls nrp-central: && rclone ls nrp-east:"]
    volumeMounts:
      - name: secret-vol-cephs3-rclone-config
        readOnly: true
        mountPath: "/root/.config/rclone/"
  imagePullSecrets:
    - name: regcred
