apiVersion: v1
kind: Pod
metadata:
  name: test-ffmpeg
spec:
  containers:
  - name: test-ffmpeg-pod
    image: gitlab-registry.nrp-nautilus.io/c3lab/workload-migration/ffmpeg_alpine:5.1.2
    resources:
      limits:
        memory: 100Mi
        cpu: 100m
      requests:
        memory: 100Mi
        cpu: 100m
    command: ["ffmpeg", "-version"]
  restartPolicy: Never
  imagePullSecrets:
    - name: regcred
