apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: test.cephfs.uswest
spec:
  storageClassName: rook-cephfs
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 4200Mi
